# Generated by Django 2.2.2 on 2019-10-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainDish',
            fields=[
                ('main_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'main_dish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('salad', models.IntegerField()),
                ('dessert', models.IntegerField()),
            ],
            options={
                'db_table': 'options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('admin', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
            ],
            options={
                'db_table': 'user_option',
                'managed': False,
            },
        ),
    ]
